%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(hbase_thrift).
-behaviour(thrift_service).


-include("hbase_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% enableTable(This, TableName)
function_info('enableTable', params_type) ->
  {struct, [{1, string}]}
;
function_info('enableTable', reply_type) ->
  {struct, []};
function_info('enableTable', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% disableTable(This, TableName)
function_info('disableTable', params_type) ->
  {struct, [{1, string}]}
;
function_info('disableTable', reply_type) ->
  {struct, []};
function_info('disableTable', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% isTableEnabled(This, TableName)
function_info('isTableEnabled', params_type) ->
  {struct, [{1, string}]}
;
function_info('isTableEnabled', reply_type) ->
  bool;
function_info('isTableEnabled', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% compact(This, TableNameOrRegionName)
function_info('compact', params_type) ->
  {struct, [{1, string}]}
;
function_info('compact', reply_type) ->
  {struct, []};
function_info('compact', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% majorCompact(This, TableNameOrRegionName)
function_info('majorCompact', params_type) ->
  {struct, [{1, string}]}
;
function_info('majorCompact', reply_type) ->
  {struct, []};
function_info('majorCompact', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getTableNames(This)
function_info('getTableNames', params_type) ->
  {struct, []}
;
function_info('getTableNames', reply_type) ->
  {list, string};
function_info('getTableNames', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getColumnDescriptors(This, TableName)
function_info('getColumnDescriptors', params_type) ->
  {struct, [{1, string}]}
;
function_info('getColumnDescriptors', reply_type) ->
  {map, string, {struct, {'hbase_types', 'ColumnDescriptor'}}};
function_info('getColumnDescriptors', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getTableRegions(This, TableName)
function_info('getTableRegions', params_type) ->
  {struct, [{1, string}]}
;
function_info('getTableRegions', reply_type) ->
  {list, {struct, {'hbase_types', 'TRegionInfo'}}};
function_info('getTableRegions', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% createTable(This, TableName, ColumnFamilies)
function_info('createTable', params_type) ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'ColumnDescriptor'}}}}]}
;
function_info('createTable', reply_type) ->
  {struct, []};
function_info('createTable', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}},
          {3, {struct, {'hbase_types', 'AlreadyExists'}}}]}
;
% deleteTable(This, TableName)
function_info('deleteTable', params_type) ->
  {struct, [{1, string}]}
;
function_info('deleteTable', reply_type) ->
  {struct, []};
function_info('deleteTable', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% get(This, TableName, Row, Column, Attributes)
function_info('get', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {map, string, string}}]}
;
function_info('get', reply_type) ->
  {list, {struct, {'hbase_types', 'TCell'}}};
function_info('get', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getVer(This, TableName, Row, Column, NumVersions, Attributes)
function_info('getVer', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i32},
          {5, {map, string, string}}]}
;
function_info('getVer', reply_type) ->
  {list, {struct, {'hbase_types', 'TCell'}}};
function_info('getVer', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getVerTs(This, TableName, Row, Column, Timestamp, NumVersions, Attributes)
function_info('getVerTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i64},
          {5, i32},
          {6, {map, string, string}}]}
;
function_info('getVerTs', reply_type) ->
  {list, {struct, {'hbase_types', 'TCell'}}};
function_info('getVerTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRow(This, TableName, Row, Attributes)
function_info('getRow', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {map, string, string}}]}
;
function_info('getRow', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRow', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRowWithColumns(This, TableName, Row, Columns, Attributes)
function_info('getRowWithColumns', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, string}},
          {4, {map, string, string}}]}
;
function_info('getRowWithColumns', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRowWithColumns', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRowTs(This, TableName, Row, Timestamp, Attributes)
function_info('getRowTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, i64},
          {4, {map, string, string}}]}
;
function_info('getRowTs', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRowTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRowWithColumnsTs(This, TableName, Row, Columns, Timestamp, Attributes)
function_info('getRowWithColumnsTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, string}},
          {4, i64},
          {5, {map, string, string}}]}
;
function_info('getRowWithColumnsTs', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRowWithColumnsTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRows(This, TableName, Rows, Attributes)
function_info('getRows', params_type) ->
  {struct, [{1, string},
          {2, {list, string}},
          {3, {map, string, string}}]}
;
function_info('getRows', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRows', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRowsWithColumns(This, TableName, Rows, Columns, Attributes)
function_info('getRowsWithColumns', params_type) ->
  {struct, [{1, string},
          {2, {list, string}},
          {3, {list, string}},
          {4, {map, string, string}}]}
;
function_info('getRowsWithColumns', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRowsWithColumns', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRowsTs(This, TableName, Rows, Timestamp, Attributes)
function_info('getRowsTs', params_type) ->
  {struct, [{1, string},
          {2, {list, string}},
          {3, i64},
          {4, {map, string, string}}]}
;
function_info('getRowsTs', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRowsTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRowsWithColumnsTs(This, TableName, Rows, Columns, Timestamp, Attributes)
function_info('getRowsWithColumnsTs', params_type) ->
  {struct, [{1, string},
          {2, {list, string}},
          {3, {list, string}},
          {4, i64},
          {5, {map, string, string}}]}
;
function_info('getRowsWithColumnsTs', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('getRowsWithColumnsTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% mutateRow(This, TableName, Row, Mutations, Attributes)
function_info('mutateRow', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, {struct, {'hbase_types', 'Mutation'}}}},
          {4, {map, string, string}}]}
;
function_info('mutateRow', reply_type) ->
  {struct, []};
function_info('mutateRow', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% mutateRowTs(This, TableName, Row, Mutations, Timestamp, Attributes)
function_info('mutateRowTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, {struct, {'hbase_types', 'Mutation'}}}},
          {4, i64},
          {5, {map, string, string}}]}
;
function_info('mutateRowTs', reply_type) ->
  {struct, []};
function_info('mutateRowTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% mutateRows(This, TableName, RowBatches, Attributes)
function_info('mutateRows', params_type) ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'BatchMutation'}}}},
          {3, {map, string, string}}]}
;
function_info('mutateRows', reply_type) ->
  {struct, []};
function_info('mutateRows', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% mutateRowsTs(This, TableName, RowBatches, Timestamp, Attributes)
function_info('mutateRowsTs', params_type) ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'BatchMutation'}}}},
          {3, i64},
          {4, {map, string, string}}]}
;
function_info('mutateRowsTs', reply_type) ->
  {struct, []};
function_info('mutateRowsTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% atomicIncrement(This, TableName, Row, Column, Value)
function_info('atomicIncrement', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i64}]}
;
function_info('atomicIncrement', reply_type) ->
  i64;
function_info('atomicIncrement', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% deleteAll(This, TableName, Row, Column, Attributes)
function_info('deleteAll', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {map, string, string}}]}
;
function_info('deleteAll', reply_type) ->
  {struct, []};
function_info('deleteAll', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% deleteAllTs(This, TableName, Row, Column, Timestamp, Attributes)
function_info('deleteAllTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i64},
          {5, {map, string, string}}]}
;
function_info('deleteAllTs', reply_type) ->
  {struct, []};
function_info('deleteAllTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% deleteAllRow(This, TableName, Row, Attributes)
function_info('deleteAllRow', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {map, string, string}}]}
;
function_info('deleteAllRow', reply_type) ->
  {struct, []};
function_info('deleteAllRow', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% increment(This, Increment)
function_info('increment', params_type) ->
  {struct, [{1, {struct, {'hbase_types', 'TIncrement'}}}]}
;
function_info('increment', reply_type) ->
  {struct, []};
function_info('increment', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% incrementRows(This, Increments)
function_info('incrementRows', params_type) ->
  {struct, [{1, {list, {struct, {'hbase_types', 'TIncrement'}}}}]}
;
function_info('incrementRows', reply_type) ->
  {struct, []};
function_info('incrementRows', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% deleteAllRowTs(This, TableName, Row, Timestamp, Attributes)
function_info('deleteAllRowTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, i64},
          {4, {map, string, string}}]}
;
function_info('deleteAllRowTs', reply_type) ->
  {struct, []};
function_info('deleteAllRowTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerOpenWithScan(This, TableName, Scan, Attributes)
function_info('scannerOpenWithScan', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TScan'}}},
          {3, {map, string, string}}]}
;
function_info('scannerOpenWithScan', reply_type) ->
  i32;
function_info('scannerOpenWithScan', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerOpen(This, TableName, StartRow, Columns, Attributes)
function_info('scannerOpen', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, string}},
          {4, {map, string, string}}]}
;
function_info('scannerOpen', reply_type) ->
  i32;
function_info('scannerOpen', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerOpenWithStop(This, TableName, StartRow, StopRow, Columns, Attributes)
function_info('scannerOpenWithStop', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {list, string}},
          {5, {map, string, string}}]}
;
function_info('scannerOpenWithStop', reply_type) ->
  i32;
function_info('scannerOpenWithStop', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerOpenWithPrefix(This, TableName, StartAndPrefix, Columns, Attributes)
function_info('scannerOpenWithPrefix', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, string}},
          {4, {map, string, string}}]}
;
function_info('scannerOpenWithPrefix', reply_type) ->
  i32;
function_info('scannerOpenWithPrefix', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerOpenTs(This, TableName, StartRow, Columns, Timestamp, Attributes)
function_info('scannerOpenTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {list, string}},
          {4, i64},
          {5, {map, string, string}}]}
;
function_info('scannerOpenTs', reply_type) ->
  i32;
function_info('scannerOpenTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerOpenWithStopTs(This, TableName, StartRow, StopRow, Columns, Timestamp, Attributes)
function_info('scannerOpenWithStopTs', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {list, string}},
          {5, i64},
          {6, {map, string, string}}]}
;
function_info('scannerOpenWithStopTs', reply_type) ->
  i32;
function_info('scannerOpenWithStopTs', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% scannerGet(This, Id)
function_info('scannerGet', params_type) ->
  {struct, [{1, i32}]}
;
function_info('scannerGet', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('scannerGet', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% scannerGetList(This, Id, NbRows)
function_info('scannerGetList', params_type) ->
  {struct, [{1, i32},
          {2, i32}]}
;
function_info('scannerGetList', reply_type) ->
  {list, {struct, {'hbase_types', 'TRowResult'}}};
function_info('scannerGetList', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% scannerClose(This, Id)
function_info('scannerClose', params_type) ->
  {struct, [{1, i32}]}
;
function_info('scannerClose', reply_type) ->
  {struct, []};
function_info('scannerClose', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
% getRowOrBefore(This, TableName, Row, Family)
function_info('getRowOrBefore', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string}]}
;
function_info('getRowOrBefore', reply_type) ->
  {list, {struct, {'hbase_types', 'TCell'}}};
function_info('getRowOrBefore', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% getRegionInfo(This, Row)
function_info('getRegionInfo', params_type) ->
  {struct, [{1, string}]}
;
function_info('getRegionInfo', reply_type) ->
  {struct, {'hbase_types', 'TRegionInfo'}};
function_info('getRegionInfo', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% append(This, Append)
function_info('append', params_type) ->
  {struct, [{1, {struct, {'hbase_types', 'TAppend'}}}]}
;
function_info('append', reply_type) ->
  {list, {struct, {'hbase_types', 'TCell'}}};
function_info('append', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}}]}
;
% checkAndPut(This, TableName, Row, Column, Value, Mput, Attributes)
function_info('checkAndPut', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {5, string},
          {6, {struct, {'hbase_types', 'Mutation'}}},
          {7, {map, string, string}}]}
;
function_info('checkAndPut', reply_type) ->
  bool;
function_info('checkAndPut', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'IOError'}}},
          {2, {struct, {'hbase_types', 'IllegalArgument'}}}]}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

